# Generated by Django 6.0.5 on 2026-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeticionCreacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('pegi', models.CharField(choices=[('PEGI3', 'PEGI 3'), ('PEGI7', 'PEGI 7'), ('PEGI12', 'PEGI 12'), ('PEGI16', 'PEGI 16'), ('PEGI18', 'PEGI 18')], default='PEGI3', max_length=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('categorias', models.CharField(max_length=255)),
                ('plataformas', models.CharField(max_length=255)),
                ('mensaje_usuario', models.TextField(blank=True, null=True)),
                ('fecha_peticion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDA', 'Cumplida'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugerenciaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('pegi', models.CharField(choices=[('PEGI3', 'PEGI 3'), ('PEGI7', 'PEGI 7'), ('PEGI12', 'PEGI 12'), ('PEGI16', 'PEGI 16'), ('PEGI18', 'PEGI 18')], default='PEGI3', max_length=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('categorias', models.CharField(max_length=255)),
                ('plataformas', models.CharField(max_length=255)),
                ('mensaje_usuario', models.TextField(blank=True, null=True)),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDA', 'Cumplida'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
