# Generated by Django 6.0.5 on 2026-05-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peticioncreacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_peticiones_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sugerenciacambio',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_cambio', to='juegos.juego'),
        ),
        migrations.AddField(
            model_name='sugerenciacambio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_sugerencias_cambio', to=settings.AUTH_USER_MODEL),
        ),
    ]
