# Generated by Django 6.0.5 on 2026-05-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadojuego',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_listas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(related_name='juegos', to='juegos.categoria'),
        ),
        migrations.AddField(
            model_name='estadojuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_listas_usuarios', to='juegos.juego'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='juegos.juego'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_opiniones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinion',
            name='plataforma_jugado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.plataforma'),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(related_name='juegos', to='juegos.plataforma'),
        ),
        migrations.AlterUniqueTogether(
            name='estadojuego',
            unique_together={('usuario', 'juego')},
        ),
    ]
